# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gsshift_pb2 as gsshift__pb2


class SshiftStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Runner = channel.unary_unary(
        '/gsshift.Sshift/Runner',
        request_serializer=gsshift__pb2.Input.SerializeToString,
        response_deserializer=gsshift__pb2.Output.FromString,
        )


class SshiftServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Runner(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SshiftServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Runner': grpc.unary_unary_rpc_method_handler(
          servicer.Runner,
          request_deserializer=gsshift__pb2.Input.FromString,
          response_serializer=gsshift__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gsshift.Sshift', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
